plugins { id 'com.android.application' }

android {
    namespace 'jp.sabaepixcells.earth'
    compileSdk 35

    defaultConfig {
        applicationId 'jp.sabaepixcells.earth'
        minSdk 26
        targetSdk 35
        versionCode 1
        versionName '001'
    }

    buildTypes {
        release { minifyEnabled false }
        debug {
            versionNameSuffix '-dev'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
